version: '3.8'

services:
  apkmanager:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./apk-storage:/app/apk-storage
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1 